### ISSUE TITLE
--

### ISSUE THREAD

**Issue by robodhruv** [sandeshkalantre/ppt#1]
Random stalking and tried to play the game.. Does it have any requisite packages? none mentioned..

If not, it doesn't really launch! :cry: 
update readme maybe?

**Comment by alankarkotwal** [comment]
Its not a game! Its just a simulation we ran to figure out common patterns emerging on random plays of a three-person version of Tic-Tac-Toe. 😛

**Comment by sandeshkalantre** [comment]
LOL, didn't work on this for more than the initial 2 hours. It was basically a random late night ideation on the possible rules for 3 person Tic-Tac-Toe.
